name = "q1-flat"
stan_file = "q1-flat.stan"
prepared_data_dir = "q1"
stan_input_function = "get_stan_input_q1"
modes = ["prior", "posterior"]

[dims]
a_vessel_type = ["vessel_type"]
b_age = ["vessel_type", "treatment"]
b_age_pred = ["vessel_type"]
a_protocol = ["vessel_type", "treatment"]
a_treatment = ["treatment"]
a_mouse = ["vessel_type", "treatment", "mouse"]
tau_mouse = ["treatment"]

[stanc_options]
warn-pedantic = true

[sample_kwargs]
save_warmup = false
iter_warmup = 3000
iter_sampling = 1000
adapt_delta = 0.99

