name = "pressure"
stan_file = "pressure.stan"
prepared_data_dir = "q2"
stan_input_function = "get_stan_input_q2"
modes = []

[dims]
a_age = ["age"]
lambda = ["mouse"]
delta = ["mouse"]
log_pressure_std_hat = ["observation"]
yrep = ["observation"]
y = ["measurement_type", "observation"]

[stanc_options]
warn-pedantic = true

[sample_kwargs]
save_warmup = false
iter_warmup = 1000
iter_sampling = 1000
adapt_delta = 0.95
