inferences_to_run = [
  # "whisker-big",
  # "whisker-ind",
  # "flow-basic-speed",
  # "flow-basic-flux",
  # "flow-big-speed",
  # "flow-big-flux",
  # "pulsatility-basic",
  # "pulsatility-basic-full",
  # "pulsatility-interaction",
  # "pulsatility-interaction-full",
  # "pulsatility-interaction-lognormal-full",
  # "pulsatility-pressure",
  # "pulsatility-pressure-no-age",
  # "hypertension-big",
  # "hypertension-basic",
  # "density",
  "diameter",
  # "tortuosity",
  # "pressure"
]
