resource_path: ["..", "plots"]
bibliography: bibliography.bib
citestyle: ieee.csl
reference-location: margin
toc: true
pdf-engine-opts:
    - '--shell-escape'

crossref:
  thm-prefix: "Question"
  thm-title: "Question"
  thm-labels: alpha a

format:
  pdf: default
  html:
    embed-resources: true
    include-in-header: mathjax.html

project:
  type: manuscript

manuscript:
  article: index.md
  notebooks: []

