resource_path: ["../"]
bibliography: bibliography.bib
citestyle: ieee.csl
reference-location: margin
toc: true

crossref:
  thm-prefix: "Question"
  thm-title: "Question"
  thm-labels: alpha a

format:
  html:
    embed-resources: true
    include-in-header: mathjax.html
#  pdf: default

project:
  type: manuscript

manuscript:
  article: index.md
  notebooks: []

