---
title: How to damage the brains of sick mice with drugs and lasers
subtitle: Teddy's first look at this question
format:
  html:
    embed_resources: true
---

This study aimed to measure how age and disease affect the ability of blood
vessels in mouse brains respond to different forms of stress. Specifically, the
study stressed the vessels by inducing hypertension and administering
precapillary sphincter ablation, and then measured vessel diameters and blood
flow. The mice included some old and some adult mice, and some healthy mice
and others with Alzheimers disease.

# What happened in the experiments?

In this study some mice were subjected to an experimental protocol designed to
investigate how the blood vessels in their brains respond to stress. First,
each mouse's blood pressure was increased using a drug, then allowed to return
to normal. Next the mouse was given a treatment called "ablation" in which
structures in the vessels that transport blood to the interior of their brains
were destroyed using a laser. Finally, the mouse's blood pressure was increased
again using the drug.

During this protocol various measurements happened: 

* Volume scans aiming to measure the diameters of different kinds of blood
vessel at a relatively coarse timescale, but with relatively good coverage of
vessels. These were done before and after treatment with the hypertension
inducing drug and before and after whisker stimulation (i.e. literally
stimulating the mouse's whiskers) at different points in the protocol.

* Diameter line scans aiming to measure the diameter of a single vessel over a
small timescale. From this scan not only the diameter but also the extent of
the vessel's diameter oscillation and center point oscillation can be estimated
by Fourier transforming the time series of diameter measurements.

* Speed line scans aiming to measure the rate at which red blood cells travel
through a single vessel. This is both in the sense of how fast does a single
cell move, and in the sense of how many cells pass through the vessel per
second.

* Blood pressure measurements at the femoral artery.

# Aims

These are the research questions that we want to answer

## 1. Does ageing affect diameter responses of blood vessels?

Specifically:

> Do vessels respond differently to whisker stimulation with ageing (as has
  been previously shown for precapillary sphincters), after acute hypertensive
  response or after precapillary sphincter ablation?

## 2.	Does ageing affect capillary diameter and centre position pulsatility?

> a) Is pulsatility affected by an acute hypertensive challenge and/or after
> ablation of the precapillary sphincter?
>
> b) Does bulb have higher pulsatility than the capillaries (this may indicate
> a protective role of the bulb in absorbing potentially damaging pulsations)?
>
> c) Does the diameter of the PA or the precapillary sphincter affect
> pulsatility in capillaries?

## 3. Does ageing affect the capillary RBC velocity/flux in capillaries?

> a) Does an acute hypertensive challenge and/or a precapillary sphincter
> ablation affect the capillary RBC velocity/flux?
>
> b) How deep into the capillary network (which capillary order) can this
> change be detected after a precapillary sphincter ablation?
>
> c) How do the diameter changes during an acute hypertensive challenge or
> after sphincter ablation relate to RBC velocity/flux changes?

# Teddy's questions

How safe is it to assume that the vessels return completely to normal after the
first hypertension treatment?

Power of center point is not sensitive to vessel type as it is caused by
things that propagate quickly throughout the brain (big far away vessels). More
function of age and treatment.
